GSM8k with assertions notebook
stanfordnlp/dspy pull request #1028
Opened 2024-05-16 01:39 UTC by Shangyint

2024-05-20 20:03 UTC, arnavsinghvi11 requested changes

2024-05-20 20:03 UTC, arnavsinghvi11 commented on examples/math/gsm8k/gsm8k_assertions.ipynb
> +        "    !pip install git+https://github.com/stanfordnlp/dspy.git@accenture-course\n",
does this notebook need to install from this branch? I believe the latest changes here have been merged to main

2024-05-20 20:03 UTC, arnavsinghvi11 commented on examples/math/gsm8k/gsm8k_assertions.ipynb
> +        "prediction = basic_math_solver(question=\"What is 1+1+1?\")\n",
the cache seems to break for me here on just this query. the rest works however!

2024-05-20 20:04 UTC, arnavsinghvi11 commented
Thanks @Shangyint ! left a few comments regarding the notebook. should be good to merge after that.

2024-05-30 18:47 UTC, Shangyint commented
@arnavsinghvi11 Thanks! Fixed both issues.

2024-05-31 04:16 UTC, arnavsinghvi11 commented
Thanks!

2024-05-31 04:16 UTC, merged