fix(evaluate): fix evaluate dict merge for pydantic
stanfordnlp/dspy pull request #1490
Opened 2024-09-13 20:20 UTC by MSNP1381

it had error when your module's output was a pydantic object rather that a dict

2024-09-18 18:26 UTC, arnavsinghvi11 requested changes
Thanks @MSNP1381 ! left some minor comments to avoid extraneous changes to`gpt3.py` but the changes to `evaluate` LGTM

2024-09-18 18:26 UTC, arnavsinghvi11 commented on dsp/modules/gpt3.py
> +def is_module_installed(module_name):
just curious why this is needed. does the try/except block not take care of this check if langfuse is not supported?

2024-09-18 18:26 UTC, arnavsinghvi11 commented on dsp/modules/gpt3.py
> +    # TODO: add test suite to me.
remove extra code

2024-09-20 15:12 UTC, MSNP1381 commented
> Thanks @MSNP1381 ! left some minor comments to avoid extraneous changes to`gpt3.py` but the changes to `evaluate` LGTM

i just added the code comments but the merge function is unstable be cause there is varying type of output for modules. My opinion is either we just use pydantic Object or any inherited objects or user have to follow some basic interfaces (as simple as dict interface))

2024-10-10 07:25 UTC, closed without merging

2024-10-10 12:15 UTC, MSNP1381 commented
@okhat can i talk to you through the email?