Add GPT-4 Vision API wrapper
stanfordnlp/dspy pull request #682
Opened 2024-03-20 03:12 UTC by jmanhype

Introduce a new GPT4Vision class in visionopenai.py that wraps the GPT-4 Vision API. This abstraction layer simplifies the process of making requests to the API for analyzing images. Key functionality includes:

Encoding images to base64
Preparing image metadata in the required format
Calculating token costs for images
Making API requests with both text and image prompts Error handling and validation

2024-03-20 20:21 UTC, isaacbmiller commented
Also is there any way to add tests for this?

2024-03-22 03:06 UTC, isaacbmiller reviewed
Also run "ruff check . --fix-only"

2024-03-22 03:06 UTC, isaacbmiller commented
> I have a unittest created.

Where?

2024-03-29 14:35 UTC, landworth commented
Adding GPT-4 Vision capabilties would be super useful! Any progress with fixing the failing check here? 🙂

2024-03-30 22:13 UTC, chitianhao commented
Did you try whether this really works or not?

What does the Signature look like to pass an image?

2024-04-01 18:01 UTC, arnavsinghvi11 commented
Thanks @jmanhype for the contribution! Could you resolve https://github.com/stanfordnlp/dspy/pull/682#pullrequestreview-1950064068? 

Also, it would be great if you add documentation for this under the [documentation folder as with the other LMs](https://github.com/stanfordnlp/dspy/tree/main/docs/api/language_model_clients). Thanks!

2024-04-04 14:19 UTC, jmanhype commented
I just made those updates

2024-04-04 21:47 UTC, arnavsinghvi11 commented on dsp/modules/visionopenai.py
> +import openai
@jmanhype tagging you here for this change

2024-04-04 22:07 UTC, arnavsinghvi11 commented
@jmanhype 

> Also run "ruff check . --fix-only"



>  add documentation for this under the [documentation folder as with the other LMs](https://github.com/stanfordnlp/dspy/tree/main/docs/api/language_model_clients). Thanks!

2024-04-05 00:55 UTC, jmanhype commented
Done

2024-04-05 04:45 UTC, arnavsinghvi11 commented
@jmanhype did you push? don't see new commits.

2024-04-09 02:20 UTC, jmanhype commented
ok everything has been updated

2024-04-09 04:02 UTC, arnavsinghvi11 requested changes

2024-04-09 04:02 UTC, arnavsinghvi11 commented on dsp/modules/visionopenai.py
> +                # You can perform additional URL validation if needed
remove extra comments

2024-04-09 04:02 UTC, arnavsinghvi11 commented on dsp/modules/visionopenai.py
> +                # You can perform additional base64 validation if needed
remove extra comments

2024-04-09 04:02 UTC, arnavsinghvi11 commented on dsp/modules/visionopenai.py
> +    # Add any additional methods needed for specific GPT-4 Vision API functionalities.
remove extra comments (or leave as TODO)

2024-04-09 04:02 UTC, arnavsinghvi11 commented
Hi @jmanhype still needs `ruff check . --fix-only` to be run.

Also, to properly call `dspy.GPT4Vision`, you need to import it as the other LM modules:
- [dsp module initialization](https://github.com/stanfordnlp/dspy/blob/e655d2233fcd70bbb3efea474086954b420f9b3a/dsp/modules/__init__.py#L11)
- [dspy module initialization](https://github.com/stanfordnlp/dspy/blob/e655d2233fcd70bbb3efea474086954b420f9b3a/dspy/__init__.py#L36)

2024-05-18 14:51 UTC, jmanhype commented
Ruff check is false positive it passes locally

2024-07-23 11:29 UTC, AyushPibit1234 commented
@arnavsinghvi11 Is there any update on this? 
cc : @jmanhype

2024-07-23 15:41 UTC, jmanhype commented
Just needs to be merged the ruff error is a false positive

2024-07-24 04:35 UTC, isaacbmiller commented
Hey @jmanhype I did actually find a ruff error and I added GPT4Vision to the __init__ files in dsp and dspy like @arnavsinghvi11 mentioned.

See this branch: 
[https://github.com/stanfordnlp/dspy/tree/jmanhype/main](https://github.com/stanfordnlp/dspy/tree/jmanhype/main)

2024-11-01 23:54 UTC, closed without merging