feature(dspy): Add Milvus in Retrieve
stanfordnlp/dspy pull request #737
Opened 2024-03-29 08:52 UTC by jaelgu

Add MilvusRM to support retrieval for Milvus or Zilliz Cloud:
- milvus: https://github.com/milvus-io/milvus
- Zilliz Cloud: https://zilliz.com

2024-04-02 22:15 UTC, arnavsinghvi11 commented
Thanks @jaelgu ! Looks great! Could you also add some documentation mirroring some of the current Retrieval Model Client integrations? (e.g. for [ChromadbRM](https://dspy-docs.vercel.app/api/retrieval_model_clients/ChromadbRM))

Will merge the PR after that!

2024-04-03 09:45 UTC, jaelgu commented
> Thanks @jaelgu ! Looks great!
> 
> Looks like couple of the tests are failing. Can you run:
> 
> 1. `ruff check . --fix-only`
> 2. `poetry install --no-interaction`
>    Seeing this error:
> 
> ```
> Installing dependencies from lock file
> Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
> 
> Because dspy depends on pymilvus (^2.3.7) which doesn't match any versions, version solving failed.
> ```
> 
> Could you also add some documentation mirroring some of the current Retrieval Model Client integrations? (e.g. for [ChromadbRM](https://dspy-docs.vercel.app/api/retrieval_model_clients/ChromadbRM))
> 
> Will merge the PR after that!

Hi, thank you for feedback. I've followed instructions to update codes and added docs.

2024-04-04 21:29 UTC, arnavsinghvi11 commented
Hi @jaelgu , thanks for the additions. 

The PR is failing the poetry.lock test with this error:

```
Run poetry install --no-interaction
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because dspy depends on pymilvus (^2.3.6) which doesn't match any versions, version solving failed.
```

Can you rebase this PR to the main branch, and then run `poetry lock --no-update` and commit the changed `poetry.lock` file? It is key to rebase to the latest version on main since the `poetry.lock` hash and updates need to be maintained. lmk if you have any questions on this.

2024-04-07 09:24 UTC, jaelgu commented
> Hi @jaelgu , thanks for the additions.
> 
> The PR is failing the poetry.lock test with this error:
> 
> ```
> Run poetry install --no-interaction
> Installing dependencies from lock file
> Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
> 
> Because dspy depends on pymilvus (^2.3.6) which doesn't match any versions, version solving failed.
> ```
> 
> Can you rebase this PR to the main branch, and then run `poetry lock --no-update` and commit the changed `poetry.lock` file? It is key to rebase to the latest version on main since the `poetry.lock` hash and updates need to be maintained. lmk if you have any questions on this.

Hello, thank you for help! I've updated the `poetry.lock` after running `poetry lock --no-update` at local.

2024-04-08 18:15 UTC, arnavsinghvi11 requested changes

2024-04-08 18:15 UTC, arnavsinghvi11 commented on poetry.lock
> +name = "isodate"
same comment as above

2024-04-08 18:15 UTC, arnavsinghvi11 commented on poetry.lock
> +name = "pymilvus"
this one is good to keep :)

2024-04-08 18:15 UTC, arnavsinghvi11 commented
Thanks @jaelgu ! looks good to merge, pending the checks on the extra dependencies added to poetry.lock.

2024-04-09 01:57 UTC, jaelgu commented on poetry.lock
> +name = "argon2-cffi"
Yes this is required by pymilvus. Pymilvus requires "minio", which requires "argon2-cffi".

2024-04-09 01:58 UTC, jaelgu commented on poetry.lock
> +name = "azure-core"
pymilvus requires "azure-storage-blob", which requires "azure-core".

2024-04-09 01:59 UTC, jaelgu commented on poetry.lock
> +name = "environs"
yes, "environs" is required by pymilvus.
<img width="830" alt="image" src="https://github.com/stanfordnlp/dspy/assets/86251631/a4fbb0b3-154b-4a30-b476-50535a9e5ec7">

2024-04-09 02:00 UTC, jaelgu commented on poetry.lock
> +name = "isodate"
pymilvus requires "azure-storage-blob", which requires "isodate".

2024-04-09 02:01 UTC, jaelgu commented on poetry.lock
> +name = "marshmallow"
pymilvus requires "environs", which requires "mashmallow".

2024-04-09 02:01 UTC, jaelgu commented on poetry.lock
> +name = "minio"
yes, "minio" is required by pymilvus.

2024-04-09 02:02 UTC, jaelgu commented on poetry.lock
> +name = "pycryptodome"
pymilvus requires "minio", which requires "pycrytodome".

2024-04-09 03:32 UTC, jaelgu commented
> Thanks @jaelgu ! looks good to merge, pending the checks on the extra dependencies added to poetry.lock.

I've replied to the comments and it turns out all extra dependencies are required by pymilvus.

2024-04-09 03:52 UTC, merged

2024-04-09 03:52 UTC, arnavsinghvi11 commented
Thanks @jaelgu for checking!