fix rational type in the api documentation.
stanfordnlp/dspy pull request #851
Opened 2024-04-17 06:11 UTC by habanoz

This PR addresses issue #841.

- Modify API documentation for class ChainOfThought to reflect the correct rationale_type according to the up-to-date source.
  - Provide a simple example to show how to specify a custom rationale
- Modify API documentation for class ChainOfThoughtWithHint to reflect correct rationale_type according to the up-to-date source.

2024-04-17 15:16 UTC, isaacbmiller requested changes

2024-04-17 15:16 UTC, isaacbmiller commented on docs/api/modules/ChainOfThought.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
I believe it should be dspy.OutputField

2024-04-17 15:16 UTC, isaacbmiller commented on docs/api/modules/ChainOfThought.md
> +            desc="${produce the answer}. We ...",
Lets clarify that it might not only be producing an answer. Could be any last key

2024-04-17 15:16 UTC, isaacbmiller commented on docs/api/modules/ChainOfThoughtWithHint.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
Same as above

2024-04-17 17:54 UTC, habanoz commented on docs/api/modules/ChainOfThought.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
Good point

2024-04-17 17:55 UTC, habanoz commented on docs/api/modules/ChainOfThoughtWithHint.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
Ok.

2024-04-25 08:50 UTC, habanoz commented on docs/api/modules/ChainOfThoughtWithHint.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
chanted to dpsy.

2024-04-25 08:50 UTC, habanoz commented on docs/api/modules/ChainOfThought.md
> +- `rationale_type` (_dsp.OutputField_, _optional_): Rationale type for reasoning steps. Defaults to `None`.
chanted to dpsy.

2024-04-26 16:24 UTC, merged